# Generated by Django 3.2.5 on 2021-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
